### ISSUE TITLE
Cross-Origin headers for public API

### ISSUE THREAD

**Issue by DenisKolodin** [exonum/exonum#263]
I cannot use Exonum REST API directly if static assets (html, css, js) loaded from other server:
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource`.

How about to add `Access-Control-Allow-Origin` header and make it configurable through `config.toml`?
```
[api]
domain = "<valid domain or *>"
```

Or will we recommend to use reverse-proxy (nginx) with CORS headers to access Exonum node?

**Comment by quicky84** [comment]
For the time being one can use the following workaround:
```
use iron::headers::{AccessControlAllowOrigin};
```
and in the `wire` method
```
// self_.ok_response(&serde_json::to_value(&json).unwrap())

let ok_res = self_.ok_response(&serde_json::to_value(&json).unwrap());
let mut res = ok_res.unwrap();
res.headers.set(AccessControlAllowOrigin::Any);
Ok(res)
```

**Comment by quicky84** [comment]
I will add here one more reason why it's rather necessary.
Public endpoints such as 
`/api/explorer/v1/blocks/some_block`,
`/api/system/v1/transactions/some_hash`
are not accessible from a browser because of cross-origin. And because these endpoints are coded in exonum itself, it seems to be out of reach for developers to fix them within the framework.

If there no programmatical way to fix in it within the framework, this (plugin for chrome)[https://chrome.google.com/webstore/detail/moesif-origin-cors-change/digfbfaphojjndkpccljibejjbppifbc?hl=en] might come in handy.

**Comment by DenisKolodin** [comment]
Solved with https://github.com/exonum/exonum/pull/406
