### ISSUE TITLE
Public built-in endpoint for transactions (patially) fails

### ISSUE THREAD

**Issue by quicky84** [exonum/exonum#343]
The `"content"` field of JSON received accessing `/system/v1/transactions/some_hash` is always `null`. `some_hash` is a hash of some known committed transaction. According to the [documentation](https://exonum.com/doc/advanced/node-management/#known-committed-transaction-response-example) this field must contain the original tx.

To reproduce:
1. Clone  the cryptocurrency example
2. Compile, start
3. Run `examples/test.sh`. This will submit 3 tx and their hashes will be returned.
4. Use any of  the returned hashes to access `/system/v1/transactions/hash`.

**Comment by slowli** [comment]
Hi! The issue indeed exists; it is related to the fact that the transactions in the demo do not override the default [`info()`](https://github.com/exonum/exonum/blob/6273e1aad4635a94ff6534ad1e291a5702dada47/exonum/src/blockchain/service.rs#L59) method implementation, [which is used by the blockchain explorer module](https://github.com/exonum/exonum/blob/6273e1aad4635a94ff6534ad1e291a5702dada47/exonum/src/explorer/mod.rs#L76). So, to fix this right now, you would need to redefine the `info()` method as something like

```rust
impl Transaction for TxTransfer {
    // other methods

    fn info(&self) -> serde_json::Value {
        serde_json::to_value(self).expect("Cannot serialize transaction to JSON")
    }
}
```

We are planning to come up with a more complete solution in the upcoming releases (e.g., make this the default implementation for `info()`, or refactor `info()` otherwise).

**Comment by quicky84** [comment]
Thanks, cool, it works! I would suggest mentioning this [here](https://exonum.com/doc/advanced/node-management/#public-endpoints), otherwise the docs give a wrong impression.
