### ISSUE TITLE
Provide Windows OS Support

### ISSUE THREAD

**Issue by lazaridiscom** [exonum/exonum#431]
#### Expected Behavior

Development on Windows OS is supported

#### Actual Behavior

Problems with Windows OS (see #363)

#### Issue at Hand

What are the plans/priorities to make Windows OS a supported platform?

**Comment by slowli** [comment]
Just in case: Exonum not supporting Windows means that it *may* not work, not that it *cannot* work on Windows. From my personal experience, Exonum core and other repos work fine on my PC with Win 8.1, rustc 1.23 stable with the MSVC 2015 compiler (the latter may be the differentiator - #363 reports an error for the GNU toolchain). If you have failure reports regarding building Exonum on Windows, they would be much appreciated!

**Comment by lazaridiscom** [comment]
The thing is that the docs state this:

### Actual Behaviour

>Windows
> 
> Workability is not guaranteed yet.

from: https://exonum.com/doc/get-started/install/#windows

### Draft

Possibly you should publish your information related Windows, thus it becomes clear that its not a "conceptual does-totally-not-work-on-windowsOS".

(I will most possibly try with the latest free MS toolchain (think its 2017) on win10, but will most possibly abort my evaluation if too much problems come up)

P.S.: personally i'm waiting for a good reason to overcome my lazyness to install (again) Ubuntu on my laptop.

**Comment by slowli** [comment]
> The thing is that the docs state this:

I don't see a problem with this, tbh. It says "workability is not guaranteed" (as in: "we cannot guarantee that Exonum will work on your particular Windows setup"), not "Exonum will not work on Windows".

> Possibly you should publish your information related Windows

Once we gather more information what works and what doesn't and find out best practices / patterns, sure, that's what we will do. Thanks for advice! For now, we simply don't have this information in a satisfyingly complete form. 

> P.S.: personally i'm waiting for a good reason to overcome my lazyness to install (again) Ubuntu on my laptop.

A suggestion just in case: you most probably already know this, but you can install a virtual machine  for Windows (such as [VirtualBox](https://www.virtualbox.org/)) instead of installing Ubuntu on the physical machine. This is what I use as the main dev environment. I suppose using a cloud provider with SSH access may be an even simpler option from the deployment perspective, but it may cost money.

**Comment by lazaridiscom** [comment]
You should really provide this information for people who need it (like I would have needed it).

I'm aware of VM/Cloud etc., but I do not like them.

**Comment by slowli** [comment]
It seems that part of your issue concerns documentation. I propose the following follow-up regarding this particular part:

- I submit a PR to the docs rewording the Windows support information
- You're free to comment on it, of course

Thus, we won't be getting off-topic here.
