### ISSUE TITLE
fix Demo so it is a safe application

### ISSUE THREAD

**Issue by mark-watson** [exonum/exonum#440]
*(You can write your issue in a free form,
    or you can use the template below)*

#### Expected Behavior

The demo blockchain should be a complete safe example that could be used safely.

#### Actual Behavior

The demo has a warning that since Fork is used, data is read/write when it should be read only.

I was interested in using exodus until I saw this warning, and some quick research indicated that it would take a casual user real effort to fix this defect.

#### Specifications

- Version:

- Platform:

- Subsystem:

#### Additional info

Provide as much information as possible:

- Code snippets that cause the problem.

- Full backtrace of the bug (run with enviroment variable RUST_BACKTRACE=full).

- Log (run with enviroment variable RUST_LOG=trace).

- Other info that could help us to find the problem.

**Comment by DarkEld3r** [comment]
@mark-watson Thank you for the report, but could you please clarify what demo you are building? If possible, copy the warning message here.

**Comment by slowli** [comment]
@DarkEld3r I think @mark-watson is talking about the `cryptocurrency` repository (if this is the case, the issue should probably belong there, but as I clarify below, it's mostly solved already). There is a warning in the [service creation tutorial](https://exonum.com/doc/get-started/create-service/) saying that it's not the best idea to make a schema wrapper around `&mut Fork`. This is [already fixed](https://github.com/exonum/cryptocurrency/blob/8fc094a527fb6aa17cc7ae84dce929542c1ce47e/src/lib.rs#L106) in the cryptocurrency code, and is going to be fixed in the tutorial as well once exonum/exonum-doc#144 is merged.

**Comment by mark-watson** [comment]
Thanks, sounds good!
