### ISSUE TITLE
Node's memory leak?

### ISSUE THREAD

**Issue by avacom** [exonum/exonum#930]
Exonum: 0.9.1
rustc: 1.28.0

Good day! We are now trying to test the uptime of a node. We have 4 nodes launched on a Windows PC. Independent from this, we have 3 nodes on a Linux PC. On both systems, we see slow but constant growth of the RAM consumption

Windows:
- Uptime: 3 days
- Start RAM (single node): ~300 Mb
- Current RAM (single node): ~680 Mb
- Transaction producing:
1. Node 1: 1 trx every 5 sec
2. Node 2: 1 trx every 5 sec
3. Node 3: 1 trx every 5 sec
4. Node 4: 1 trx every 5 sec

Linux:
- Uptime: 2 days
- Start RAM (single node): ~200 Mb
- Current RAM (single node): ~360 Mb
- Transaction producing:
1. Node 1: 1 trx every 1 min
2. Node 2: 1 trx every 1 min
3. Node 3: 1 trx every 2 min

We thought, it might be some memory leak issue. Do you have any idea about it?

**Comment by vldm** [comment]
Hello Andriy, under the hood exonum uses RocksDB, which is a journaling database.

This means that before changing the data on the disk, an entry about these changes is created in the log.
https://github.com/facebook/rocksdb/wiki/Write-Ahead-Log

This log has a upper size limit, i.e. he can not fill all the memory.

But since this log exists, the data on the disk can be more than expected, but after the node is restarted, the database will start to recover, which will make it clear the log and free some amount of memmory.

Also, there is a https://github.com/facebook/rocksdb/wiki/MemTable in the RocsDB which makes some of the last records to be stored explicitly in the RAM.

Among other things, the OS has disk buffers, which will also mirror some amount of memory used on the disk.

In this ticket the dynamics of database growth is not shown. It is very likely that growth has a upper limit.

Based on all these factors, we can conclude that most likely there are no memory leaks.

But to make sure, we will do some audit just after end of our architecture refactoring.
